// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: person.sql

package dbcontext

import (
	"context"
)

const getPerson = `-- name: GetPerson :one
select id, first_name, last_name from Person
where id = ? limit 1
`

func (q *Queries) GetPerson(ctx context.Context, id int64) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i Person
	err := row.Scan(&i.ID, &i.FirstName, &i.LastName)
	return i, err
}
